# Copyright 2023 Ram Rachum and collaborators.
# This program is distributed under the MIT license.

DEFAULT_EPISODE_LENGTH = 40
DEFAULT_N_GENERATIONS = 5_000
DEFAULT_N_TUNE_SAMPLES = 5
DEFAULT_TRAIN_BATCH_SIZE = 500 # 4_000
DEFAULT_LEARNING_RATE = 6e-06

DEFAULT_MEAN_HANDICAP = 5
DEFAULT_HANDICAP_DIFFERENCE = 3
DEFAULTS_RANDOMIZE_LABELS = True